org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod Properties
mod_version=1.0.0
maven_group=fr.loxoz.mods
archives_base_name=NeoBetterWaystonesMenu
mod_id=neobetterwaystonesmenu
mod_author=LoxozForkByCremon

# NeoForge properties
minecraft_version=1.21.1
neoforge_version=21.1.77

# Dependencies (Modrinth maven exige o sufixo +neoforge-1.21.1)
balm_version=21.0.56+neoforge-1.21.1
waystones_version=21.1.27+neoforge-1.21.1
